import type { SVGProps } from "react";
import { COLORS, MARK, STACKED } from "@/lib/logo-paths";

// The FrancoBridge mark and its lockup, the name always under the bridge, as flat vector paths: the arch
// bridge with the Peace Tower. The text is outlined from Marcellus, so nothing
// here depends on a font loading. Geometry is generated by brand/tools/build-logo.py.
//
// Marcellus has one weight, so the type is weighted up with a stroke in its own
// colour. The bridge, the tower and the type take one colour; the maple leaf is always
// red, except in the one-colour version, where it is cut out of the tower.

export type LogoSurface = "blue" | "ivory" | "mono";
export type LogoVariant = "stacked" | "mark";

// The logo navy, red and ivory, plus the site's brand blue for UI accents.
export const BRAND = { ...COLORS, blue: "#0E397F" } as const;

type Props = Omit<SVGProps<SVGSVGElement>, "color"> & {
  variant?: LogoVariant;
  /** The surface the logo sits on. "mono" draws everything in currentColor. */
  on?: LogoSurface;
};

export function Logo({ variant = "stacked", on = "ivory", ...props }: Props) {
  const box = variant === "stacked" ? STACKED : MARK;
  const ink = on === "blue" ? BRAND.ivory : on === "ivory" ? BRAND.navy : "currentColor";
  const label = variant === "mark" ? "FrancoBridge" : "FrancoBridge Consulting Inc.";

  return (
    <svg
      viewBox={`${box.x} ${box.y} ${box.width} ${box.height}`}
      role="img"
      aria-label={label}
      {...props}
    >
      <path fill={ink} d={MARK.arch} />
      <path fill={ink} d={MARK.frame} />
      {on === "mono" ? (
        <path fill={ink} fillRule="evenodd" d={MARK.tower + MARK.leaf} />
      ) : (
        <>
          <path fill={ink} d={MARK.tower} />
          <path fill={BRAND.red} d={MARK.leaf} />
        </>
      )}
      {variant === "stacked" && (
        <>
          <path fill={ink} stroke={ink} strokeWidth={STACKED.wordStroke} strokeLinejoin="round" d={STACKED.word} />
          <path fill={ink} stroke={ink} strokeWidth={STACKED.descriptorStroke} strokeLinejoin="round" d={STACKED.descriptor} />
        </>
      )}
    </svg>
  );
}

export default Logo;
