import type { SVGProps } from "react";
import { HORIZONTAL, MARK, STACKED } from "@/lib/logo-paths";

// The FrancoBridge mark and its two lockups, as flat vector paths. The text is
// outlined (Fraunces for the name, Fredoka for the descriptor), so nothing here
// depends on a font loading. Geometry is generated by brand/tools/build-logo.py.
//
// The stone (the bridge) and the type take one colour; the arch band takes the
// surface's colour; the sun is always red, except in the one-colour version,
// where the band becomes a true cutout. On a tinted surface (a pastel band,
// a gradient) the band is a cutout too, so the surface shows through the arch.

export type LogoSurface = "blue" | "ivory" | "tint" | "mono";
export type LogoVariant = "stacked" | "horizontal" | "mark";

export const BRAND = {
  blue: "#0E397F",
  red: "#DB2517",
  ivory: "#F6F4F2",
} as const;

type Props = Omit<SVGProps<SVGSVGElement>, "color"> & {
  variant?: LogoVariant;
  /** The surface the logo sits on. "mono" draws everything in currentColor. */
  on?: LogoSurface;
};

export function Logo({ variant = "horizontal", on = "ivory", ...props }: Props) {
  const box =
    variant === "stacked" ? STACKED : variant === "horizontal" ? HORIZONTAL : MARK;
  const stone = on === "blue" ? BRAND.ivory : on === "mono" ? "currentColor" : BRAND.blue;
  const band = on === "blue" ? BRAND.blue : on === "ivory" ? BRAND.ivory : null;
  const sun = on === "mono" ? "currentColor" : BRAND.red;
  const label = variant === "mark" ? "FrancoBridge" : "FrancoBridge Consulting Inc.";

  return (
    <svg
      viewBox={`0 0 ${box.width} ${box.height}`}
      role="img"
      aria-label={label}
      {...props}
    >
      <path fill={stone} d={MARK.stone} />
      {band && <path fill={band} d={MARK.band} />}
      <path fill={sun} d={MARK.dome} />
      {variant !== "mark" && (
        <>
          <path fill={stone} d={(box as typeof STACKED).word} />
          <path fill={stone} d={(box as typeof STACKED).descriptor} />
        </>
      )}
    </svg>
  );
}

export default Logo;
